from __future__ import annotations

import argparse
import sys

import pandas as pd

from umutextstats.output import write_output
from umutextstats.summary.aggregate import aggregate_features


def add_aggregate_arguments(
    parser: argparse.ArgumentParser,
) -> None:
    parser.add_argument(
        "features",
        help="Features CSV generated by analyze",
    )

    parser.add_argument(
        "--metadata",
        required=True,
        help="Original dataset containing grouping columns",
    )

    parser.add_argument(
        "--group-by",
        required=True,
        help="Metadata column used for grouping",
    )

    parser.add_argument(
        "--id-column",
        default="id",
        help="Shared identifier column",
    )

    parser.add_argument(
        "-o",
        "--output",
        default=None,
        help="Output aggregate file. If omitted, prints to stdout.",
    )


def run_aggregate(args: argparse.Namespace) -> None:
    
    if args.features == "-" and args.metadata == "-":
        raise ValueError(
            "features and metadata cannot both be read from stdin"
        )
    
    if args.features == "-":
        features = pd.read_csv(sys.stdin)
    else:
        features = pd.read_csv(args.features)

    if args.metadata == "-":
        metadata = pd.read_csv(sys.stdin)
    else:
        metadata = pd.read_csv(args.metadata)

    if args.id_column not in features.columns:
        raise ValueError(
            f"ID column '{args.id_column}' not found in features file."
        )

    if args.id_column not in metadata.columns:
        raise ValueError(
            f"ID column '{args.id_column}' not found in metadata file."
        )

    if args.group_by not in metadata.columns:
        available = ", ".join(metadata.columns)
        raise ValueError(
            f"Group column '{args.group_by}' not found in metadata file. "
            f"Available columns: {available}"
        )

    merged = features.merge(
        metadata[[args.id_column, args.group_by]],
        on=args.id_column,
        how="left",
    )

    aggregate = aggregate_features(
        merged,
        group_by=args.group_by,
        exclude={args.id_column, args.group_by},
    )

    if args.output:
        write_output(aggregate, args.output)
    else:
        print(aggregate.to_json(orient="records", indent=2))