# src/umutextstats/cli/summarize.py

from __future__ import annotations

import argparse

import pandas as pd

from umutextstats.output import write_output
from umutextstats.summary.summarize import (
    summarize_features,
    summarize_features_long,
)


def add_summarize_arguments(parser: argparse.ArgumentParser) -> None:
    parser.add_argument(
        "input",
        help="Input features file generated by UMUTextStats",
    )

    parser.add_argument(
        "-o",
        "--output",
        default="summary.csv",
        help="Output summary file path. Supported: .csv, .json",
    )

    parser.add_argument(
        "--format",
        choices=["auto", "long", "nested"],
        default="auto",
        help=(
            "Summary output shape. "
            "'long' is recommended for CSV, 'nested' for JSON. "
            "'auto' chooses based on output extension."
        ),
    )


def run_summarize(args: argparse.Namespace) -> None:
    features = pd.read_csv(args.input)

    output = args.output.lower()

    if args.format == "long":
        summary = summarize_features_long(features)

    elif args.format == "nested":
        summary = summarize_features(features)

    elif output.endswith(".csv"):
        summary = summarize_features_long(features)

    else:
        summary = summarize_features(features)

    write_output(summary, args.output)