directory_folder: es
includes:
- es/phonetics.yaml
- es/morphosyntax.yaml
- es/errors.yaml
- es/semantics.yaml
- es/pragmatics.yaml
- es/stylometry.yaml
- es/lexical.yaml
- es/psycholinguistic-processes.yaml
- es/register.yaml
- es/digital-communication.yaml
- es/syntax.yaml
