dimensions:
- key: phonetics
  class: CompositeDimension
  strategy: CompositeStrategySum
  children:
  - key: phonetics-expressive-lengthening
    class: CompositeDimension
    strategy: CompositeStrategySum
    description: Drawing out or emphasizing verbalized words or repeated emojis
    children:
    - key: phonetics-expressive-lengthening-text
      class: PatternDimension
      description: Drawing out or emphasizing a verbalized word with repeated letters
      pattern: (\p{L})\1{3,}
      input_column: text_raw
      validation:
        cases: tests/feature_cases/phonetics_lengthening.yaml

    - key: phonetics-expressive-lengthening-emojis
      class: PatternDimension
      description: Repetition of the same emoji for expressive emphasis
      pattern: (\p{Extended_Pictographic})\1{2,}
      input_column: text_raw
      validation:
        cases: tests/feature_cases/phonetics_lengthening_emojis.yaml