dimensions:
- key: stylometry
  children:
  - key: stylometry-corpus
    children:
    - key: stylometry-corpus-length
      class: LengthDimension
      description: Counts the length of the text
    - key: stylometry-corpus-words-count
      class: WordCountDimension
      description: Counts how many words there are in the text
    - key: stylometry-corpus-syllabes-count
      class: SyllableCountDimension
      description: Counts how many syllabes there are in the text
    - key: stylometry-corpus-syllabes-per-word
      class: SyllablePerWordDimension
      description: Counts how many syllabes there per word
    - key: stylometry-corpus-words-per-sentence
      class: WordPerSentenceDimension
      description: The average number of words per sentence

    - key: stylometry-corpus-TTR
      class: RTIEDimension
      description: Standardized ratios TTR
      separator: whole
    - key: stylometry-corpus-TTR-standard
      class: RTIEDimension
      description: TTR (by chunks)
      separator: by-chunks
    - key: stylometry-corpus-TTR-deviation
      class: RTIEDeviationDimension
      description: TTR (by chunks)
      separator: by-chunks

    - key: stylometry-corpus-readability
      class: ReadabilityDimension
      description: Measures the readability within of the text
    - key: stylometry-corpus-inflesz
      class: PerspicuityDimension
      description: Measures the perspicuity within of the text

    - key: stylometry-corpus-uppercase
      class: WordCase
      description: The average number of words written in uppercase
      comparator: upper
    - key: stylometry-corpus-titlecase
      class: WordCase
      description: The average number of words written in titlecase
      comparator: title

    - key: stylometry-corpus-expressions-quoted
      class: PatternDimension
      description: Counts how many quoted expressions
      pattern: '["“‘''«][\p{L}\p{N}\s\-\,\.]{4,64}[”"’''»]'
      percentage: false
      separator: whole
    - key: stylometry-corpus-expressions-within-parenthesis
      class: PatternDimension
      description: Counts how many expressions within paranthesis
      pattern: '\([\p{L}\p{N}\s\-\,\.]{4,64}\)'
      percentage: false
    - key: stylometry-corpus-expressions-within-asterisks
      class: PatternDimension
      description: Counts how many expressions within asterisks
      pattern: '\*[\p{L}\p{N}\s\-\,\.]{4,64}\*'
      percentage: false

    - key: stylometry-corpus-words-length-avg
      class: AverageWordLengthDimension
      description: The average length of the words
    - key: stylometry-corpus-words-longer-6ltr
      class: WordLengthDimension
      description: The number of words bigger than 6 characters
      comparator: '>='
      length: '6'

  - key: stylometry-sentences
    children:
    - key: stylometry-sentences-count
      class: SentenceCountDimension
      description: Counts how many sentences there are in the text
    - key: stylometry-sentences-exclamative-percentage
      class: PatternDimension
      description: Counts how many exclamative sentences there are in the text
      pattern: '[\p{L}\p{N}\s]+[\!]+'
      separator: by-sentence
    - key: stylometry-sentences-exclamative-percentage-emphasis
      class: PatternDimension
      description: Counts how many exclamative sentences there are in the text
      pattern: '[\p{L}\p{N}\s]+[\!]{2,}'
      separator: by-sentence
    - key: stylometry-sentences-interrogative-percentage
      class: PatternDimension
      description: Counts how many exclamative sentences there are in the text with more than "?"
      pattern: '[\p{L}\p{N}\s]+[\?]+'
      separator: by-sentence
    - key: stylometry-sentences-interrogative-percentage-emphasis
      class: PatternDimension
      description: Counts how many interrogative sentences there are in the text with more than one "?"
      pattern: '[\p{L}\p{N}\s]+[\?]{2,}'
      separator: by-sentence
    - key: stylometry-sentences-quotes-percentage
      class: PatternDimension
      description: Counts how many quoted sentences
      pattern: '^[“"][\p{L}\p{N}\s]+["”]$'
      separator: by-sentence
    - key: stylometry-sentences-conversations
      class: PatternDimension
      description: Counts how many sentences simulate a conversation
      pattern: '[-—–][\s\¿¡]*\p{L}+'
      separator: by-sentence

  - key: stylometry-punctuation
    children:
    - key: stylometry-punctuation-prime
      class: CharacterFrequencyDimension
      description: Percentage of prime symbols
      character: '′‴″'
    - key: stylometry-punctuation-currencies
      class: CharacterFrequencyDimension
      description: Percentage of symbols used as currency symbols
      character: '€$£'
    - key: stylometry-punctuation-apostrophe
      class: CharacterFrequencyDimension
      description: Percentage of apostrohpes, can be used to measure units or in Elision of words
      character: '’'''
    - key: stylometry-punctuation-brackets-open
      class: CharacterFrequencyDimension
      description: Percentage of open curly brackets
      character: '{[(〔'
    - key: stylometry-punctuation-curly-brackets-close
      class: CharacterFrequencyDimension
      description: Percentage of closed curly brackets
      character: '}])〕'
    - key: stylometry-punctuation-quotation-open
      class: CharacterFrequencyDimension
      description: Percentage of quotation open symbols
      character: '"“‘''''«'
    - key: stylometry-punctuation-quotation-close
      class: CharacterFrequencyDimension
      description: Percentage of quotation close symbols
      character: '”"’''»'
    - key: stylometry-punctuation-colons
      class: CharacterFrequencyDimension
      description: Percentage of colons
      character: ':ː：∶'
      removeemojis: 'true'
    - key: stylometry-punctuation-semicolons
      class: CharacterFrequencyDimension
      description: Percentage of semicolons
      character: ';'
    - key: stylometry-punctuation-dashes
      class: CharacterFrequencyDimension
      description: Percentage of dash symbols
      character: '-—–'
    - key: stylometry-punctuation-low-dashes
      class: CharacterFrequencyDimension
      description: Percentage of low dashed
      character: '_'
    - key: stylometry-punctuation-fullstop
      class: CharacterFrequencyDimension
      description: Percentage of fullstops
      character: '.'
    - key: stylometry-punctuation-commas
      class: CharacterFrequencyDimension
      description: Percentage of commas
      character: ',ʻ،、︐︑﹐﹑，､'
    - key: stylometry-punctuation-ellipsis
      class: PatternDimension
      description: Percentage of ellipsis
      pattern: '…|\.{3,}'
      input_column: text_raw
      separator: by-spaces
    - key: stylometry-punctuation-open-question
      class: CharacterFrequencyDimension
      description: Percentage of open question symbol
      character: '¿'
    - key: stylometry-punctuation-open-exclamation
      class: CharacterFrequencyDimension
      description: Percentage of open exclamation symbol
      character: '¡'
    - key: stylometry-punctuation-space
      class: CharacterFrequencyDimension
      description: Percentage of spaces
      character: SPACE
    - key: stylometry-punctuation-interdot
      class: CharacterFrequencyDimension
      description: Percentage of interdots
      character: '·'
    - key: stylometry-punctuation-percentages
      class: CharacterFrequencyDimension
      description: Percentage of percentages
      character: '%‰‱'
    - key: stylometry-punctuation-ampersand
      class: CharacterFrequencyDimension
      description: Percentage of ampersands
      character: '&'
    - key: stylometry-punctuation-at-sign
      class: CharacterFrequencyDimension
      description: Percentage of at sign symbols
      character: '@'
    - key: stylometry-punctuation-backslash
      class: CharacterFrequencyDimension
      description: Percentage of backslash symbols
      character: '\'
    - key: stylometry-punctuation-pipe
      class: CharacterFrequencyDimension
      description: Percentage of pipe symbols
      character: '|¦'
    - key: stylometry-punctuation-bullet
      class: CharacterFrequencyDimension
      description: Percentage of bullet symbols
      character: '•'
    - key: stylometry-punctuation-caret
      class: CharacterFrequencyDimension
      description: Percentage of caret symbols
      character: '^^‸⁁＾'
    - key: stylometry-punctuation-degree
      class: CharacterFrequencyDimension
      description: Percentage of degree symbols
      character: 'º'
    - key: stylometry-punctuation-ditto-mark
      class: CharacterFrequencyDimension
      description: Percentage of ditto marks, that expresses that the words or figures above it are to be repeated
      character: '”'
    - key: stylometry-punctuation-hash
      class: CharacterFrequencyDimension
      description: Percentage of hash symbols
      character: '#'
    - key: stylometry-punctuation-numero-sign
      class: PatternDimension
      description: Percentage of numero signs
      pattern: '(№|Nº|No,|No\.|no.)'
    - key: stylometry-punctuation-pilcrow
      class: CharacterFrequencyDimension
      description: Percentage of pilcrow symbol, that are typographical characters that mark the star of a paragraph
      character: '¶'
    - key: stylometry-punctuation-trademarks
      class: CharacterFrequencyDimension
      description: Percentage of copyright or trademark signs
      character: '©®™'
    - key: stylometry-punctuation-mathematical-signs
      class: CharacterFrequencyDimension
      description: Percentage of mathematical signs
      character: '−-≠+×*·+÷=≈~'